#!/usr/bin/env python3
"""Import every supplied SkillBuilder CSV row, without modifying the source files."""
import csv
import hashlib
import json
import pathlib
import re

WEB = pathlib.Path(__file__).resolve().parents[1]
SOURCE = WEB.parent / 'MLA-C01-SkillBuilder'
PARTS = {'Thuat ngu': 1, 'Dich vu': 2, 'Quy trinh': 3, 'Ghep tinh huong': 4}
EXPECTED = {1: [210, 76, 42, 62], 2: [164, 62, 51, 113], 3: [147, 69, 61, 127], 4: [145, 69, 60, 116]}


def build():
    workflows = json.loads((WEB / 'scripts/keyword-workflows-en.json').read_text())
    items, counts, source_files = [], {}, []
    for file in sorted(SOURCE.glob('*.csv')):
        match = re.search(r' - (Thuat ngu|Dich vu|Quy trinh|Ghep tinh huong) D([1-4])$', file.stem)
        if not match:
            raise ValueError(f'Unrecognized source: {file.name}')
        part, domain = PARTS[match[1]], int(match[2])
        rows = list(csv.reader(file.open(encoding='utf-8-sig')))
        headers, records = rows[4], rows[5:]
        assert len(records) == EXPECTED[domain][part - 1], file.name
        counts[f'{domain}.{part}'] = len(records)
        source_files.append({'file': file.name, 'rows': len(records), 'sha256': hashlib.sha256(file.read_bytes()).hexdigest()})
        for index, row in enumerate(records):
            assert len(row) == len(headers) and all(cell.strip() for cell in row), (file.name, index + 6)
            row = [cell.replace('\\n', '\n').strip() for cell in row]
            key, keywords = row[:2]
            steps = []
            if part == 3:
                translation = workflows[f'{domain}:{key}']
                digest = hashlib.sha256(json.dumps(row, ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()
                assert translation['sourceSha256'] == digest, f'Review English workflow after source change: {key}'
                steps = translation['steps']
            identifier = f'd{domain}-p{part}-' + hashlib.sha256(key.encode()).hexdigest()[:16]
            if part == 1:
                prompt, answer, task, topic, scope, urls, date = row[3], key, row[11], row[12], *row[13:16]
                fields = [('Nghĩa tiếng Việt', 2), ('Định nghĩa', 4), ('Cơ chế và giải thích', 5), ('Ví dụ và công thức', 6), ('Khi nào áp dụng', 7), ('Điểm dễ nhầm và điều kiện', 8), ('Dịch vụ liên quan', 9)]
            elif part == 2:
                prompt, answer, task, topic, scope, urls, date = row[2], key, row[11], row[12], *row[13:16]
                fields = [('Định nghĩa', 3), ('Lợi ích', 4), ('Cơ chế và quy trình', 5), ('Khi nào sử dụng', 6), ('Ví dụ', 7), ('Phân biệt và lưu ý', 8), ('Loại dịch vụ hoặc công cụ', 9)]
            elif part == 3:
                prompt = ' → '.join(steps)
                answer, task, topic, scope, urls, date = prompt, row[11], 'Quy trình', *row[12:15]
                fields = [('Chuỗi bước trong tài liệu', 2), ('Tình huống và mục tiêu', 3), ('Bước 1', 4), ('Bước 2', 5), ('Bước 3', 6), ('Bước 4 và tùy chọn', 7), ('Vì sao theo thứ tự này', 8), ('Phương án nhiễu và lý do loại', 9), ('Điều kiện, biến thể và đầu ra', 10)]
            else:
                prompt, answer, task, topic, scope, urls, date = row[2], row[4], row[8], 'Ghép tình huống', *row[9:12]
                fields = [('Tình huống tiếng Việt', 3), ('Vì sao chọn', 5), ('Phân biệt và phương án nhiễu', 6), ('Liên hệ quy trình và điểm nhớ', 7)]
            links = [url.strip() for url in urls.splitlines() if url.strip()]
            assert links and all(re.match(r'https?://', url) for url in links), (file.name, index + 6, links)
            items.append({'id': identifier, 'domain': domain, 'part': part, 'order': index + 1, 'title': key,
                          'prompt': prompt, 'answer': answer, 'keywords': keywords, 'task': task, 'topic': topic,
                          'sections': [{'title': label, 'text': row[col]} for label, col in fields],
                          'steps': steps if part == 3 else [],
                          'source': {'file': file.name, 'row': index + 6, 'scope': scope, 'urls': links, 'date': date}})
    assert len(source_files) == 16 and len(items) == 1574
    assert len({item['id'] for item in items}) == len(items), 'Duplicate source keys'
    items.sort(key=lambda item: (item['domain'], item['part'], item['order']))
    out = WEB / 'src/data'
    (out / 'keywords.json').write_text(json.dumps(items, ensure_ascii=False, indent=2) + '\n')
    (out / 'keyword-manifest.json').write_text(json.dumps({'count': len(items), 'counts': counts, 'sources': source_files}, ensure_ascii=False, indent=2) + '\n')
    (out / 'keyword-ids.ts').write_text('// Generated by scripts/import-keywords.py. Do not edit.\nexport const keywordIds = new Set(' + json.dumps([item['id'] for item in items]) + ');\n')
    print(f'Imported {len(items)} items from {len(source_files)} CSV files; all 16 Domain/Part counts match.')


if __name__ == '__main__':
    build()
