import { test, expect } from '@playwright/test';
import { emptyState, defaultSettings } from '../src/domain';
import { onboard, snapshot } from './helpers';

test('new study pools and source search use the retained questions',async({page})=>{
  await onboard(page);
  await expect(page.locator('.bank-card')).toContainText('567 câu hỏi');
  await page.goto('/#/exam');
  await expect(page.locator('.pool-count')).toContainText('507 câu');
  await page.getByLabel('Số câu hỏi',{exact:true}).fill('507');
  await page.getByRole('button',{name:'Bắt đầu thi thử',exact:true}).click();
  const ids=(await snapshot(page)).active!.questionIds;
  expect(ids).toHaveLength(507);
  for(const id of [269,271,188,295,202,193,270])expect(ids).not.toContain(id);
  await page.goto('/#/library');
  await expect(page.locator('.library-count')).toContainText('567 câu hỏi');
  await page.getByRole('textbox',{name:'Tìm câu hỏi'}).fill('#269');
  await expect(page.locator('.library-card')).toHaveCount(1);
  await expect(page.locator('.library-card-meta')).toContainText('CÂU #070');
  await page.getByRole('textbox',{name:'Tìm câu hỏi'}).fill('mls q271');
  await expect(page.locator('.library-card')).toHaveCount(1);
  await expect(page.locator('.library-card-meta')).toContainText('CÂU #081');
});

test('old sessions retain answer letters while marks and flashcards use merged groups',async({page})=>{
  const finished={id:'old-mlp',mode:'practice' as const,questionIds:[271],index:0,answers:{271:['A']},revealed:[271],flagged:[271],startedAt:1000,deadline:null,finishedAt:2000,finishReason:'manual' as const,settings:{...defaultSettings,count:1}};
  const active={...finished,id:'old-docker',questionIds:[188],answers:{188:['B']},revealed:[],flagged:[188],finishedAt:null,finishReason:null};
  const legacy={...emptyState(),updatedAt:2000,bookmarks:[269],known:[271],progress:{271:{attempts:1,correct:1,latest:true,lastSeen:2000}},history:[finished],active,flash:{ids:[70,269,271,81],index:2}};
  await page.goto('/');
  await page.evaluate(s=>localStorage.setItem('ml-practice:v1',JSON.stringify(s)),legacy);
  await onboard(page);
  await page.goto('/#/results/old-mlp');
  await expect(page.locator('.score-ring strong')).toHaveText('100%');
  await page.locator('.review-card > summary').click();
  await expect(page.locator('.answer-label')).toHaveText('Correct answer: A');
  await expect(page.locator('.archived-variant')).toContainText('#081');
  await page.goto('/#/progress');
  await page.locator('.unfinished-section').getByRole('button',{name:'Tiếp tục',exact:true}).click();
  await expect(page.locator('.question-id')).toContainText('#188');
  await expect(page.locator('.choice-button').nth(1)).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Nộp bài',exact:true}).click();
  await page.getByRole('button',{name:'Nộp và xem kết quả'}).click();
  await expect(page.locator('.score-ring strong')).toHaveText('100%');
  const history=(await snapshot(page)).history;
  expect(history.find(s=>s.id==='old-docker')!.answers).toEqual({188:['B']});
  expect(history.find(s=>s.id==='old-mlp')!.answers).toEqual({271:['A']});
  await page.goto('/#/flashcards');
  await expect(page.locator('.flashcard-top>.eyebrow')).toContainText('#081');
  expect((await snapshot(page)).flash).toMatchObject({ids:[70,81],index:1});
  await page.getByRole('button',{name:'Lật thẻ',exact:true}).click();
  await expect(page.locator('.answer-label')).toHaveText('Correct answer: D');
  await page.getByRole('button',{name:'Cần học lại',exact:true}).click();
  expect((await snapshot(page)).known).toEqual([]);
  await page.goto('/#/library');
  await page.getByRole('button',{name:'Đã lưu',exact:true}).click();
  await expect(page.locator('.library-card-meta')).toContainText('CÂU #070');
  await page.getByRole('button',{name:'Bỏ lưu câu hỏi',exact:true}).click();
  expect((await snapshot(page)).bookmarks).toEqual([]);
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('ml-practice:v1')!))).toEqual(legacy);
});
