import { test, expect } from '@playwright/test';
import { onboard } from './helpers';
import { readFileSync } from 'node:fs';
import type { KeywordItem } from '../src/keyword-domain';
const items = JSON.parse(readFileSync(new URL('../src/data/keywords.json',import.meta.url),'utf8')) as KeywordItem[];

test.beforeEach(async ({page}) => {await onboard(page); await page.getByRole('link', {name:'Keywork Practice',exact:true}).click();});
test('complete catalog filters by Domain and Part, and exposes all source details', async ({page}) => {
  await expect(page.getByRole('heading',{name:'Keywork Practice',exact:true})).toBeVisible();
  await expect(page.locator('.kw-overview')).toContainText('/ 1574');
  await page.locator('.kw-domain').nth(3).click();
  await page.locator('.kw-parts>button').nth(1).click();
  await expect(page.locator('.kw-launch')).toContainText('69 mục');
  await page.locator('.kw-catalog-toggle').first().click();
  await expect(page.locator('.kw-details')).toContainText('Định nghĩa');
  await page.getByText('Nguồn và phạm vi nội dung',{exact:true}).click();
  await expect(page.locator('.kw-source a').first()).toHaveAttribute('href',/^https:\/\//);
  await page.screenshot({path:'test-results/keywork-desktop.png',fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/keywork-mobile-viewport.png',animations:'disabled'});
  await page.screenshot({path:'test-results/keywork-mobile.png',fullPage:true,animations:'disabled'});
});
test('instant answers, keyboard, burst clicks and resume preserve the exact card and choice', async ({page,context}) => {
  await page.getByRole('button',{name:'Bắt đầu học',exact:true}).click();
  await page.keyboard.press('1');
  await expect(page.locator('.kw-feedback')).toBeVisible();
  await page.screenshot({path:'test-results/keywork-study-desktop.png',animations:'disabled'});
  const before = await page.locator('.kw-feedback p').textContent();
  await page.getByRole('button',{name:'Đánh dấu đã nắm',exact:true}).click();
  await page.reload();
  await page.getByRole('button',{name:/Tiếp tục Keywork Practice/}).click();
  await expect(page.locator('.kw-feedback p')).toHaveText(before!);
  await expect(page.getByRole('button',{name:'Đã nắm',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.locator('.kw-choice').first().evaluate(button => {for(let i=0;i<20;i++) (button as HTMLButtonElement).click();});
  await expect(page.locator('.kw-study-top')).toContainText('2/20');
  await expect(page.locator('.kw-feedback')).toHaveCount(0);
  await page.keyboard.press('2'); await expect(page.locator('.kw-feedback')).toBeVisible();
  await page.keyboard.press('Space'); await expect(page.locator('.kw-study-top')).toContainText('3/20');
  const other = await context.newPage(); await other.goto('/');
  await other.locator('.saved-learners button').filter({hasText:'Duy'}).click();
  await other.getByRole('link',{name:'Keywork Practice',exact:true}).click();
  await expect(other.locator('.kw-overview>div>strong')).toContainText('1 / 1574');
  await other.getByRole('button',{name:/Tiếp tục Keywork Practice/}).click();
  await expect(other.locator('.kw-study-top')).toContainText('3/20');
});
test('workflow cloze uses English steps and keeps conditional notes in Vietnamese', async ({page}) => {
  await page.locator('.kw-domain').first().click(); await page.locator('.kw-parts>button').nth(2).click();
  await page.getByLabel('Tìm kiến thức Keywork').fill('P01');
  await page.getByRole('button',{name:'Bắt đầu học',exact:true}).click();
  await expect(page.locator('.kw-prompt')).toContainText('________');
  const workflow = items.find(q => q.domain === 1 && q.part === 3 && q.order === 1)!;
  const prompt = await page.locator('.kw-prompt').textContent();
  const answer = workflow.steps.find(step => !prompt!.includes(step))!;
  await page.getByRole('button',{name:new RegExp(`^[1-4]\\. ${answer}$`)}).click();
  await expect(page.locator('.kw-feedback')).toContainText('Chính xác');
  await expect(page.locator('.kw-details')).toContainText('crawler không là điều kiện bắt buộc');
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading',{name:'Đã hoàn thành 1 mục'})).toBeVisible();
});
test('flashcards and mastery filters save per learner without auto-marking correct answers as mastered', async ({page}) => {
  await page.getByLabel('Cách học').selectOption('cards');
  await page.getByRole('button',{name:'Bắt đầu học',exact:true}).click();
  await page.keyboard.press('Space'); await expect(page.locator('.kw-feedback')).toContainText('Đáp án và ghi nhớ');
  await page.getByRole('button',{name:'Cần ôn lại',exact:true}).click();
  await page.getByRole('button',{name:'Lưu và về danh mục'}).click();
  await page.getByLabel('Trạng thái',{exact:true}).selectOption('review');
  await expect(page.locator('.kw-catalog-item')).toHaveCount(1);
  await expect(page.locator('.kw-overview>div>strong')).toContainText('0 / 1574');
  await page.getByLabel('Tìm kiến thức Keywork').fill('does-not-exist');
  await expect(page.getByRole('button',{name:'Bắt đầu học',exact:true})).toBeDisabled();
});
