import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { onboard, snapshot } from './helpers';
import type { Question } from '../src/domain';
const bank:Question[]=JSON.parse(readFileSync(new URL('../src/data/questions.json',import.meta.url),'utf8'));
const added=bank.filter(q=>q.origin==='udemy');
test.beforeEach(async({page})=>{await onboard(page);await page.emulateMedia({reducedMotion:'reduce'});});
test('Udemy quick practice grades answers, keeps separate progress and resumes after reload',async({page})=>{
  await page.goto('/#/practice');
  await page.getByRole('combobox',{name:'Nội dung',exact:true}).selectOption('701-895');
  await expect(page.locator('.pool-count')).toContainText('195 câu');
  await page.getByLabel('Số câu hỏi',{exact:true}).fill('10');
  await page.getByRole('button',{name:'Theo thứ tự',exact:true}).click();
  await page.getByRole('button',{name:/^Học nhanh/}).click();
  await page.getByRole('button',{name:'Bắt đầu luyện tập',exact:true}).click();
  const q=added[0];
  await expect(page.locator('.question-origin')).toContainText('Udemy');
  await expect(page.locator('.duplicate-matches')).toBeVisible();
  for(const a of q.answer)await page.locator('.choice-button').nth(Object.keys(q.choices).indexOf(a)).click();
  await expect(page.locator('.answer-analysis')).toBeVisible();
  await expect(page.locator('.source-answer-note')).toContainText('Udemy');
  await page.reload();
  expect((await snapshot(page)).progress[q.id].correct).toBe(1);
  expect((await snapshot(page)).progress[q.duplicateMatches![0].questionId]).toBeUndefined();
  await page.getByRole('button',{name:'Câu tiếp',exact:true}).click();
  await expect(page.locator('.question-id')).toContainText(`#${added[1].id}`);
  await page.reload();expect((await snapshot(page)).active!.index).toBe(1);
});
test('Udemy loop supports wrong retry, adds the next card, and retains its source',async({page})=>{
  await page.clock.install();
  await page.goto('/#/flashcards');
  await page.getByLabel('Nguồn câu hỏi',{exact:true}).selectOption('udemy');
  await expect(page.locator('.flash-loop-window li')).toHaveCount(10);
  const q=added[0],wrong=Object.keys(q.choices).filter(a=>!q.answer.includes(a)).slice(0,q.required);
  for(const a of wrong)await page.locator('.choice-button').nth(Object.keys(q.choices).indexOf(a)).click();
  await expect(page.locator('.feedback-banner')).toContainText('Chưa đúng');
  await page.clock.fastForward(200);
  for(const a of q.answer)await page.locator('.choice-button').nth(Object.keys(q.choices).indexOf(a)).click();
  await expect(page.locator('.feedback-banner')).toContainText('Đúng rồi');
  await page.clock.fastForward(200);
  await page.keyboard.press('Enter');
  await expect(page.locator('.flashcard-top>.eyebrow')).toContainText(`#${added[1].id}`);
  await page.reload();await expect(page.getByLabel('Nguồn câu hỏi',{exact:true})).toHaveValue('udemy');
  expect((await snapshot(page)).progress[q.id].attempts).toBe(2);
});
test('library labels retained duplicates and renders repaired ordering items on mobile',async({page})=>{
  await page.goto('/#/library');
  await page.getByLabel('Nguồn câu hỏi',{exact:true}).selectOption('udemy');
  await expect(page.locator('.library-count strong')).toHaveText('195 câu hỏi');
  const duplicate=added.find(q=>q.duplicateMatches?.[0].kind==='exact')!;
  await page.getByRole('textbox',{name:'Tìm câu hỏi'}).fill(`#${duplicate.id}`);
  await page.locator('.library-card > details > summary').click();
  await expect(page.locator('.duplicate-matches')).toContainText('Trùng nguyên văn');
  await page.getByRole('textbox',{name:'Tìm câu hỏi'}).fill('#710');
  await page.locator('.library-card > details > summary').click();
  await expect(page.locator('.question-text')).toContainText('1.');
  await expect(page.locator('.question-text')).toHaveCSS('white-space','pre-line');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/udemy-ordering-mobile.png',fullPage:true,animations:'disabled'});
});
