import { ArrowRight, BookOpen, Check, Clock3, Flag, Layers3, Play, Sparkles, Target, TrendingUp } from 'lucide-react';
import type { Question, Session, State } from './domain';
import { formatTime, score, studyQuestions, hasQuestionMark, questionProgress } from './domain';

export default function Home({ state, bank, go, quick, unfinished, resume }: { state: State; bank: Question[]; go: (path: string) => void; quick: () => void; unfinished: Session | null; resume: (id: string) => void }) {
  const questions = studyQuestions(bank);
  const attempted = questions.filter(q=>questionProgress(q,state)).length, known = questions.filter(q=>hasQuestionMark(q,state.known)).length;
  const totalAttempts = Object.values(state.progress).reduce((n, p) => n + p.attempts, 0);
  const correct = Object.values(state.progress).reduce((n, p) => n + p.correct, 0);
  const studyDays = new Set([...Object.values(state.progress).map(p => new Date(p.lastSeen).toLocaleDateString('vi-VN')), ...state.history.map(s => new Date(s.finishedAt!).toLocaleDateString('vi-VN'))]).size;
  const studied = questions.filter(q=>questionProgress(q,state)||hasQuestionMark(q,state.known)).length;
  const continuing = state.active || unfinished;
  return <div className="page home-page">
    <div className="page-heading"><div><div className="eyebrow">KHÔNG GIAN HỌC TẬP CỦA BẠN</div><h1>Mỗi ngày một chút,<br className="mobile-break" /> vững hơn từng câu.</h1><p>Ôn kiến thức, luyện phản xạ và sẵn sàng cho bài thi.</p></div><span className="day-label"><span className="live-dot" /> Sẵn sàng học tiếp</span></div>
    {continuing && <button className="resume-banner" onClick={() => state.active ? go('/session') : resume(continuing.id)}><div className="resume-icon"><Play size={19}/></div><div><strong>{state.active ? 'Tiếp tục' : 'Mở lại'} {continuing.mode === 'exam' ? 'bài thi thử' : 'phiên luyện tập'}</strong><p>Đã trả lời {Object.values(continuing.answers).filter(a => a.length).length}/{continuing.questionIds.length} câu{continuing.deadline ? ' · Đồng hồ thi vẫn đang chạy' : ''}{!state.active && ' · Tiếp tục trên tab này'}</p></div><ArrowRight size={20}/></button>}
    <section className="hero">
      <div className="hero-copy"><span className="hero-label"><Sparkles size={14} /> MỘT PHIÊN HỌC NHỎ, MỘT BƯỚC TIẾN MỚI</span><h2>10 câu hỏi.<br />Bắt đầu tạo thói quen.</h2><p>Ôn nhanh bộ đề đã nhập, xem đáp án và từ khóa ngay sau mỗi câu.<br />Bạn chỉ cần dành một chút thời gian hôm nay.</p><button className="button lime" onClick={quick}>Học nhanh 10 câu <ArrowRight size={17} /></button><span className="hero-footnote">Tiến trình được lưu tự động trên thiết bị này</span></div>
      <div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-spark">✳</div><div className="mini-card back-card"/><div className="mini-card front-card"><div className="mini-card-top"><span>ML / PRACTICE</span><Layers3 size={17}/></div><div className="mini-card-body">Small steps.<br/><em>Deep learning.</em></div><div className="mini-card-bottom"><span className="mini-check"><Check size={14}/></span><span>Mỗi câu hỏi, một điều mới</span></div></div><div className="floating-pill"><span>✦</span> Keep learning</div></div>
    </section>

    <button className="resume-banner" onClick={() => go('/keywork')}><div className="resume-icon"><BookOpen size={20}/></div><div><strong>Keywork Practice · 4 Domain</strong><p>1.574 mục · Thuật ngữ, dịch vụ, quy trình và ghép tình huống · Theo dõi phần đã nắm</p></div><ArrowRight size={20}/></button>
    <section className="stats-grid" aria-label="Thống kê học tập">
      {[{icon:BookOpen,label:'Câu đã luyện',value:attempted,suffix:`/ ${questions.length}`,hint:'Tích lũy qua mỗi phiên',color:'green'},{icon:Target,label:'Tỷ lệ trả lời đúng',value:totalAttempts ? `${Math.round(correct/totalAttempts*100)}%` : '—',suffix:'',hint:totalAttempts ? `${correct}/${totalAttempts} lượt trả lời` : 'Bắt đầu để xem thống kê',color:'blue'},{icon:Layers3,label:'Flashcard đã thuộc',value:known,suffix:`/ ${questions.length}`,hint:'Ghi nhớ theo nhịp của bạn',color:'purple'},{icon:TrendingUp,label:'Ngày đã luyện tập',value:studyDays,suffix:'ngày',hint:'Một thói quen đáng giữ',color:'orange'}].map(({icon:Icon,label,value,suffix,hint,color}) => <div className="stat-card" key={label}><div className="stat-label"><span>{label}</span><span className={`small-icon ${color}`}><Icon size={17}/></span></div><div className="stat-value">{value} <span>{suffix}</span></div><div className="stat-hint">{hint}</div></div>)}
    </section>
    <div className="section-heading"><h2>Hôm nay bạn muốn học thế nào?</h2><span>Chọn cách học phù hợp với bạn</span></div>
    <section className="mode-grid">
      {[{icon:Layers3,color:'purple',number:'01',title:'Flashcard',desc:'Lật thẻ, nhớ kiến thức. Đánh dấu đã thuộc và ôn lại những câu cần nhớ.',tags:'Lật thẻ · Tự đánh giá',route:'/flashcards',cta:'Mở bộ thẻ'},{icon:BookOpen,color:'orange',number:'02',title:'Luyện câu hỏi',desc:'Học theo bộ đề, xem giải thích ngay hoặc tự trả lời trước khi xem đáp án.',tags:'Có đáp án · Tự kiểm tra',route:'/practice',cta:'Bắt đầu luyện'},{icon:Clock3,color:'green',number:'03',title:'Thi thử',desc:'Tập trung như trong phòng thi. Tùy chọn số câu, đặt thời gian và xem kết quả.',tags:'Bấm giờ · Ẩn đáp án',route:'/exam',cta:'Tạo bài thi'}].map(({icon:Icon,...m}) => <button className={`mode-card ${m.color}`} key={m.number} onClick={() => go(m.route)}><div className="mode-card-top"><span className={`mode-icon ${m.color}`}><Icon size={25}/></span><span>{m.number}</span></div><h3>{m.title}</h3><p>{m.desc}</p><span className="mode-tags">{m.tags}</span><div className="mode-cta">{m.cta}<ArrowRight size={18}/></div></button>)}
    </section>
    <div className="bottom-grid"><section className="panel progress-panel"><div className="section-heading"><h2>Hành trình của bạn</h2><Flag size={18}/></div><div className="progress-caption"><strong>{studied}<span> / {questions.length} câu đã tiếp cận</span></strong><span>{Math.round(studied/questions.length*100)}%</span></div><div className="progress-track"><div style={{width:`${studied/questions.length*100}%`}}/></div><p>Mỗi ô là một câu hỏi. Học một ít, lấp đầy dần.</p><div className="journey-grid" aria-label={`${studied} trong ${questions.length} câu đã học`}>{questions.map(q => <span key={q.id} title={`Câu ${q.id}`} className={questionProgress(q,state)?.latest || hasQuestionMark(q,state.known) ? 'done' : questionProgress(q,state) ? 'needs-work' : ''}/>)}</div><div className="legend"><span><i className="done"/>Đã đúng / đã thuộc</span><span><i className="needs-work"/>Cần ôn lại</span><span><i/>Chưa học</span></div></section>
    <section className="panel recent-panel"><div className="section-heading"><h2>Phiên gần đây</h2><button className="text-button" onClick={() => go('/progress')}>Xem tất cả <ArrowRight size={14}/></button></div>{state.history.length ? state.history.slice(0,3).map(s => { const result=score(s,bank);return <button key={s.id} className="recent-row" onClick={() => go(`/results/${s.id}`)}><span className="recent-icon">{s.mode==='exam'?<Clock3 size={18}/>:<BookOpen size={18}/>}</span><span><strong>{s.mode==='exam'?'Thi thử':'Luyện tập'} · {s.questionIds.length} câu</strong><small>{new Date(s.finishedAt!).toLocaleDateString('vi-VN')} · {formatTime(s.finishedAt!-s.startedAt)}</small></span><b>{result.total ? `${result.percent}%` : '—'}</b></button>}) : <div className="recent-empty"><div><Clock3 size={27}/></div><h3>Phiên học đầu tiên đang chờ bạn</h3><p>Hoàn thành một phiên để xem kết quả<br/>và theo dõi sự tiến bộ ở đây.</p><button className="text-button" onClick={() => go('/practice')}>Cùng bắt đầu <ArrowRight size={14}/></button></div>}</section></div>
    <div className="source-note"><span className="live-dot"/>MLA-C01 · {questions.length} câu<span>{questions.filter(q=>q.origin==='original').length} câu tự biên soạn · {questions.filter(q=>q.status==='review').length} câu cần xác minh.</span></div>
  </div>;
}
