import { studyQuestions } from './domain';
import { useState } from 'react';
import { ArrowRight, Check, Copy, KeyRound, Laptop, RefreshCw, UserRound, Users } from 'lucide-react';
import type { Question } from './domain';
import { STORAGE_KEY } from './domain';
import { createLearner, getWriter, ProgressRepository, read } from './sync/local';
import type { Learner } from './sync/local';
import { changeSharing, cloudConfigured, restoreProfile } from './sync/cloud';

export function Welcome({ profiles, select, bank }: { profiles: Learner[]; select: (id: string) => void; bank: Question[] }) {
  const [name, setName] = useState(''), [code, setCode] = useState(() => location.hash.startsWith('#/join/') ? location.hash.slice(7) : '');
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [carry, setCarry] = useState(true);
  const hasLegacy = Boolean(read(STORAGE_KEY) && !read('ml-legacy-owner:v2'));
  const enter = (id: string) => { if (location.hash.startsWith('#/join/')) history.replaceState(null, '', '#/'); select(id); };
  const create = () => {
    try {
      const learner = createLearner(name);
      if (carry && hasLegacy) new ProgressRepository(learner, bank, getWriter()).migrateLegacy();
      enter(learner.id);
    } catch (e) { setError((e as Error).message); }
  };
  const restore = async () => {
    setBusy(true); setError('');
    try { const learner = await restoreProfile(code); enter(learner.id); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  return <main className="welcome-page"><div className="welcome-brand"><span className="brand-symbol">m<span>l</span></span>ML Practice</div><div className="welcome-grid"><section className="welcome-copy"><span className="eyebrow">CÙNG HỌC, THEO NHỊP RIÊNG</span><h1>Mỗi người một hành trình.<br/>Cùng nhau tiến bộ.</h1><p>Chọn tên để bắt đầu. Bài làm, thẻ đã thuộc và lịch sử được lưu riêng cho từng người.</p><div className="welcome-features"><span><UserRound size={18}/>Nhập tên là học</span><span><Laptop size={18}/>Mỗi tab một bài làm</span><span><Users size={18}/>Xem lịch sử được chia sẻ</span></div><div className="welcome-cloud"><span className="live-dot"/>{cloudConfigured ? 'Đã cấu hình đồng bộ Supabase' : 'Đang lưu trên trình duyệt · Chưa cấu hình Supabase'}</div></section><section className="panel welcome-card"><div className="mode-icon green"><UserRound size={26}/></div><h2>Hôm nay ai đang học?</h2><p>Không cần email hoặc mật khẩu.</p><form onSubmit={e => { e.preventDefault(); create(); }}><label className="field-label" htmlFor="learner-name">Tên người học</label><input id="learner-name" placeholder="Ví dụ: Duy" maxLength={40} required value={name} onChange={e => setName(e.target.value)} autoComplete="nickname"/><small>Trùng tên vẫn là hai hồ sơ khác nhau.</small>{hasLegacy && <label className="check-label"><input type="checkbox" checked={carry} onChange={e => setCarry(e.target.checked)}/>Chuyển tiến trình cũ trên máy vào hồ sơ này</label>}<button className="button primary" disabled={!name.trim() || busy}>Tạo hồ sơ và bắt đầu <ArrowRight size={16}/></button></form>{profiles.length > 0 && <div className="saved-learners"><span className="field-label">Hồ sơ trên trình duyệt này</span>{profiles.map(p => <button key={p.id} onClick={() => enter(p.id)}><span className="learner-avatar">{p.name.slice(0,1).toUpperCase()}</span><span><strong>{p.name}</strong><small>#{p.id.slice(0,8)}</small></span><ArrowRight size={15}/></button>)}</div>}<details className="restore-profile" open={Boolean(location.hash.startsWith('#/join/'))}><summary><KeyRound size={15}/>Tiếp tục từ thiết bị khác</summary><p>Dán mã hoặc link tiếp tục riêng của bạn. Chỉ tên người học không thể khôi phục hồ sơ.</p><form onSubmit={e => { e.preventDefault(); void restore(); }}><textarea aria-label="Mã tiếp tục học" placeholder="Dán mã hoặc link tiếp tục" value={code} onChange={e => setCode(e.target.value)} rows={3}/><button className="button secondary" disabled={!cloudConfigured || !code.trim() || busy}>{busy ? 'Đang mở hồ sơ…' : 'Mở hồ sơ bằng mã'}</button></form>{!cloudConfigured && <small>Tính năng này dùng được sau khi cấu hình Supabase.</small>}</details>{error && <p className="field-error" role="alert">{error}</p>}</section></div><footer>{studyQuestions(bank).length} câu hỏi · Flashcard · Luyện tập · Thi thử</footer></main>;
}
export function LearnerSettings({ learner, switchLearner, cloudStatus, cloudError, lastSynced, sync }: { learner: Learner; switchLearner: () => void; cloudStatus: string; cloudError: string; lastSynced: number | null; sync: () => Promise<void> }) {
  const [showCode, setShowCode] = useState(false), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const link = `${location.origin}${location.pathname}#/join/${learner.code}`;
  const copy = async (text: string) => { try { await navigator.clipboard.writeText(text); setMessage('Đã sao chép. Giữ riêng mã này để tiếp tục học trên thiết bị khác.'); } catch { setMessage('Chưa sao chép được. Bạn có thể chọn và sao chép trực tiếp mã hiển thị.'); } };
  const share = async (value: boolean) => {
    setBusy(true); setMessage('');
    try { await changeSharing(learner, value); setMessage(value ? 'Đã chia sẻ lịch sử hoàn thành. Người khác chỉ có thể xem.' : 'Đã tắt chia sẻ lịch sử.'); }
    catch (e) { setMessage((e as Error).message); } finally { setBusy(false); }
  };
  return <div className="page learner-page"><div className="page-heading"><div className="eyebrow">YOUR LEARNING PROFILE</div><h1>Xin chào, {learner.name}.</h1><p>Tiến trình riêng của bạn, dù học ở tab nào.</p></div><section className="panel learner-info"><span className="learner-avatar large">{learner.name.slice(0,1).toUpperCase()}</span><div><h2>{learner.name}</h2><p>Hồ sơ #{learner.id.slice(0,8)}</p></div><button className="button secondary" onClick={switchLearner}><Users size={16}/>Đổi người học</button></section><div className="learner-settings-grid"><section className="panel"><span className="mode-icon green"><RefreshCw size={22}/></span><h2>Lưu và đồng bộ</h2><p>{!cloudConfigured ? 'Hiện lưu trên trình duyệt. Thêm cấu hình Supabase để đồng bộ giữa các thiết bị.' : cloudStatus === 'synced' ? 'Các thay đổi đã được gửi lên Supabase.' : cloudStatus === 'error' ? 'Chưa kết nối được. Thay đổi vẫn được giữ trên máy và sẽ thử gửi lại.' : 'Đang chờ đồng bộ tiến trình lên Supabase.'}</p>{lastSynced && <small>Lần gần nhất: {new Date(lastSynced).toLocaleTimeString('vi-VN')}</small>}{cloudError && <p className="field-error">{cloudError}</p>}{cloudConfigured && <button className="button secondary" disabled={cloudStatus === 'syncing'} onClick={() => { void sync(); }}><RefreshCw size={15}/>Đồng bộ ngay</button>}</section><section className="panel"><span className="mode-icon purple"><Users size={22}/></span><h2>Lịch sử cho nhóm học</h2><p>Khi bật, người vào website có thể xem tên và các bài đã hoàn thành. Bài đang làm và quyền sửa vẫn thuộc hồ sơ này.</p><label className="check-label"><input type="checkbox" checked={learner.shared} disabled={busy} onChange={e => { void share(e.target.checked); }}/>Chia sẻ lịch sử học tập</label></section></div><section className="panel recovery-panel"><KeyRound size={25}/><div><h2>Tiếp tục trên thiết bị khác</h2><p>Mã riêng mở quyền học và lưu bài vào hồ sơ này. Không gửi mã cho nhóm; hãy dùng trang Học chung để chia sẻ lịch sử.</p>{!cloudConfigured ? <p className="subtle">Cần cấu hình Supabase trước. Hiện bạn có thể chuyển dữ liệu bằng bản sao JSON.</p> : !learner.cloudReady ? <p className="subtle">Mã sẽ sẵn sàng sau lần đồng bộ đầu tiên.</p> : <><button className="button secondary" onClick={() => setShowCode(v => !v)}>{showCode ? 'Ẩn mã tiếp tục' : 'Xem mã tiếp tục'}</button>{showCode && <div className="recovery-code"><input readOnly aria-label="Mã hồ sơ riêng" value={learner.code} onFocus={e => e.target.select()}/><div><button className="button secondary" onClick={() => { void copy(learner.code); }}><Copy size={15}/>Sao chép mã</button><button className="button primary" onClick={() => { void copy(link); }}><Copy size={15}/>Sao chép link</button></div></div>}</>}</div></section>{message && <div className="inline-message" role="status"><Check size={16}/>{message}</div>}</div>;
}
