import { ArrowLeft, ArrowRight, Bookmark, Search } from 'lucide-react';
import { useState } from 'react';
import type { Question, State } from './domain';
import { matchesOrigin, sourceLabel, studyQuestions, hasQuestionMark, setQuestionMark, relatedQuestionIds } from './domain';
import { ChoiceList, Empty, Explanation, IconToggle, QuestionAnswerStats, QuestionText, OriginTag, Tag } from './components';
import { useAssistantTopic } from './assistant-context';
export default function LibraryPage({bank,state,update}:{bank:Question[];state:State;update:(fn:(s:State)=>State)=>void}) {
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[origin,setOrigin]=useState('all'),[saved,setSaved]=useState(false),[page,setPage]=useState(0);
  const [expanded,setExpanded]=useState<number>();
  const query=search.toLowerCase().trim();
  const filtered=studyQuestions(bank).filter(q=>matchesOrigin(q,origin)&&(status==='all'||q.status===status)&&(!saved||hasQuestionMark(q,state.bookmarks))&&(!query||relatedQuestionIds(q).some(id=>String(id)===query.replace('#',''))||`${sourceLabel(q)} ${q.sourceIds.map(id=>q.collection==='mla'?`mla q${id} mla-c01 q${String(id).padStart(3,'0')}`:`mls q${String(id).padStart(3,'0')}`).join(' ')} ${q.text} ${Object.values(q.choices).join(' ')}`.toLowerCase().includes(query)));
  const current=Math.min(page,Math.max(0,Math.ceil(filtered.length/20)-1));
  const currentQuestion=filtered.slice(current*20,current*20+20).find(q=>q.id===expanded);
  useAssistantTopic(currentQuestion ? {kind:'question',id:currentQuestion.id,label:`Câu #${currentQuestion.id} · Ngân hàng câu hỏi`,study:{page:'library',selected:[],revealed:false}} : undefined);
  return <div className="page library-page"><div className="page-heading"><div className="eyebrow">YOUR QUESTION LIBRARY</div><h1>Một nơi cho mọi câu hỏi.</h1><p>Tìm theo số câu, từ khóa hoặc dịch vụ. Lưu lại những câu bạn muốn ôn kỹ.</p></div><div className="library-toolbar"><label className="search-field"><Search size={18}/><input aria-label="Tìm câu hỏi" placeholder="Tìm câu hỏi, ví dụ: SageMaker hoặc #334" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><select aria-label="Nguồn câu hỏi" value={origin} onChange={e=>{setOrigin(e.target.value);setPage(0);}}><option value="all">Tất cả nguồn</option><option value="original">Tự biên soạn · 352 câu</option><option value="imported">Bộ 286 · 242 câu sau gộp</option><option value="udemy">Udemy · 195 câu</option></select><select aria-label="Trạng thái đáp án" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">Mọi trạng thái</option><option value="checked">Đã đối chiếu</option><option value="source">Theo đáp án bộ đề</option></select><button className={`button secondary ${saved?'is-active':''}`} aria-pressed={saved} onClick={()=>{setSaved(v=>!v);setPage(0);}}><Bookmark size={16}/>Đã lưu</button></div><div className="library-count"><strong>{filtered.length} câu hỏi</strong><span>Mở câu hỏi để xem nội dung và giải thích</span></div><div className="library-list">{filtered.slice(current*20,current*20+20).map(q=><article className="panel library-card" key={q.id}><div className="library-card-meta"><span className="eyebrow">CÂU #{String(q.id).padStart(3,'0')}</span><OriginTag question={q}/><Tag status={q.status}/><IconToggle active={hasQuestionMark(q,state.bookmarks)} onClick={()=>update(s=>({...s,bookmarks:setQuestionMark(q,s.bookmarks)}))}/></div><QuestionAnswerStats question={q} state={state}/><details open={expanded===q.id} onToggle={e=>{if(e.target!==e.currentTarget)return;const open=e.currentTarget.open;setExpanded(previous=>open?q.id:previous===q.id?undefined:previous);}}><summary><span lang="en">{q.text}</span><ArrowRight size={17}/></summary><div className="library-body"><QuestionText question={q} allowHint/><ChoiceList question={q} selected={[]} disabled/><details className="show-explanation"><summary>Xem đáp án và giải thích</summary><Explanation question={q}/></details></div></details></article>)}</div>{!filtered.length&&<Empty title="Không tìm thấy câu phù hợp">Thử một từ khóa khác hoặc bỏ bộ lọc để xem thêm câu hỏi.</Empty>}{filtered.length>20&&<div className="pagination"><button className="button secondary" disabled={current===0} onClick={()=>{setPage(current-1);window.scrollTo({top:0});}}><ArrowLeft size={15}/>Trước</button><span>Trang {current+1} / {Math.ceil(filtered.length/20)}</span><button className="button secondary" disabled={(current+1)*20>=filtered.length} onClick={()=>{setPage(current+1);window.scrollTo({top:0});}}>Tiếp<ArrowRight size={15}/></button></div>}</div>;
}
