import { ArrowLeft, ArrowRight, Bookmark, Search } from 'lucide-react';
import { useState } from 'react';
import type { Question, State } from './domain';
import { ChoiceList, Empty, Explanation, IconToggle, QuestionText, Tag } from './components';
export default function LibraryPage({bank,state,update}:{bank:Question[];state:State;update:(fn:(s:State)=>State)=>void}) {
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[saved,setSaved]=useState(false),[page,setPage]=useState(0);
  const query=search.toLowerCase().trim();
  const filtered=bank.filter(q=>(status==='all'||q.status===status)&&(!saved||state.bookmarks.includes(q.id))&&(!query||String(q.id)===query.replace('#','')||`${q.text} ${Object.values(q.choices).join(' ')}`.toLowerCase().includes(query)));
  const current=Math.min(page,Math.max(0,Math.ceil(filtered.length/20)-1));
  return <div className="page library-page"><div className="page-heading"><div className="eyebrow">YOUR QUESTION LIBRARY</div><h1>Một nơi cho mọi câu hỏi.</h1><p>Tìm theo số câu, từ khóa hoặc dịch vụ. Lưu lại những câu bạn muốn ôn kỹ.</p></div><div className="library-toolbar"><label className="search-field"><Search size={18}/><input aria-label="Tìm câu hỏi" placeholder="Tìm câu hỏi, ví dụ: SageMaker hoặc #178" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><select aria-label="Trạng thái đáp án" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">Mọi trạng thái</option><option value="checked">Đã đối chiếu</option><option value="historical">Dịch vụ cũ</option><option value="review">Cần xác minh</option></select><button className={`button secondary ${saved?'is-active':''}`} aria-pressed={saved} onClick={()=>{setSaved(v=>!v);setPage(0);}}><Bookmark size={16}/>Đã lưu</button></div><div className="library-count"><strong>{filtered.length} câu hỏi</strong><span>Mở câu hỏi để xem nội dung và giải thích</span></div><div className="library-list">{filtered.slice(current*20,current*20+20).map(q=><article className="panel library-card" key={q.id}><div className="library-card-meta"><span className="eyebrow">CÂU #{String(q.id).padStart(3,'0')}</span><Tag status={q.status}/><IconToggle active={state.bookmarks.includes(q.id)} onClick={()=>update(s=>({...s,bookmarks:s.bookmarks.includes(q.id)?s.bookmarks.filter(id=>id!==q.id):[...s.bookmarks,q.id]}))}/></div><details><summary><span lang="en">{q.text}</span><ArrowRight size={17}/></summary><div className="library-body"><QuestionText question={q}/><ChoiceList question={q} selected={[]} disabled/><details className="show-explanation"><summary>Xem đáp án và giải thích</summary><Explanation question={q}/></details></div></details></article>)}</div>{!filtered.length&&<Empty title="Không tìm thấy câu phù hợp">Thử một từ khóa khác hoặc bỏ bộ lọc để xem thêm câu hỏi.</Empty>}{filtered.length>20&&<div className="pagination"><button className="button secondary" disabled={current===0} onClick={()=>{setPage(current-1);window.scrollTo({top:0});}}><ArrowLeft size={15}/>Trước</button><span>Trang {current+1} / {Math.ceil(filtered.length/20)}</span><button className="button secondary" disabled={(current+1)*20>=filtered.length} onClick={()=>{setPage(current+1);window.scrollTo({top:0});}}>Tiếp<ArrowRight size={15}/></button></div>}</div>;
}
