import { ArrowLeft, ArrowRight, CheckCircle2, ChevronLeft, Clock3, EyeOff, Flag, Grid2X2, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Question, Session, State } from './domain';
import { formatTime, isCorrect, remainingMs, revealAnswer, score, toggleChoice, hasQuestionMark, setQuestionMark } from './domain';
import { ChoiceList, Dialog, Explanation, IconToggle, QuestionText, Tag } from './components';

type Props = { session: Session; state: State; bank: Question[]; now: number; update: (fn:(s:State)=>State)=>void; go:(path:string)=>void; finish:()=>void; learnerName:string; saveLabel:string };
export default function SessionView({session,state,bank,now,update,go,finish,learnerName,saveLabel}:Props) {
  const [confirm,setConfirm] = useState(false), [palette,setPalette] = useState(false);
  const q = bank.find(q=>q.id===session.questionIds[session.index])!;
  const answers = session.answers[q.id] || [], revealed = session.revealed.includes(q.id);
  const immediate = session.mode==='practice' && session.settings.feedback==='immediate';
  const answered = Object.values(session.answers).filter(a=>a.length).length;
  const time = remainingMs(session,now);
  const navigate = (offset:number) => update(s=>s.active?{...s,active:{...s.active,index:Math.max(0,Math.min(s.active.questionIds.length-1,s.active.index+offset))}}:s);
  const choose = (letter:string) => update(s=> {
    const a=s.active;
    if(!a || a.id!==session.id || a.revealed.includes(q.id) || (a.deadline!==null && Date.now()>=a.deadline))return s;
    return {...s,active:{...a,answers:{...a.answers,[q.id]:toggleChoice(a.answers[q.id]||[],letter,q.required)}}};
  });
  useEffect(()=>{window.scrollTo({top:0});},[session.index]);
  useEffect(()=>{
    const key=(e:KeyboardEvent)=>{if(document.querySelector('dialog[open]')||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement).tagName))return;
      if(e.key==='ArrowRight'){e.preventDefault();navigate(1);}if(e.key==='ArrowLeft'){e.preventDefault();navigate(-1);}
      const letter=Object.keys(q.choices)[Number(e.key)-1];if(letter && !revealed){e.preventDefault();choose(letter);}
    };
    window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);
  });
  return <div className="session-screen"><header className="session-header"><button className="session-brand" onClick={()=>go('/')}><span className="brand-symbol small">m<span>l</span></span><span>ML Practice <small>{session.mode==='exam'?'EXAM SIMULATOR':'PRACTICE SESSION'}</small></span></button><div className="session-header-right"><button className="session-learner" onClick={()=>go('/learner')} aria-label={`Đang học: ${learnerName}`}>{learnerName}<small>{saveLabel}</small></button><div className={`session-timer ${time!==null&&time<300000?'urgent':''}`} role="timer" aria-label={time!==null?'Thời gian còn lại':'Thời gian đã học'}><Clock3 size={19}/><div><small>{time!==null?'CÒN LẠI':'ĐÃ HỌC'}</small><strong>{formatTime(time??now-session.startedAt)}</strong></div></div></div></header>
    <div className="session-subbar"><button className="text-button" onClick={()=>go('/')}><ChevronLeft size={16}/> Về tổng quan</button><span>Machine Learning · MLS / MLA-C01</span><span>{answered}/{session.questionIds.length} đã trả lời</span></div>
    <div className="session-layout"><main className="panel question-panel"><div className="question-toolbar"><div><span className="eyebrow">CÂU {String(session.index+1).padStart(2,'0')} / {session.questionIds.length}</span><span className="question-id">Ngân hàng #{String(q.id).padStart(3,'0')}</span></div><div className="question-tools"><Tag status={q.status}/><IconToggle active={hasQuestionMark(q,state.bookmarks)} onClick={()=>update(s=>({...s,bookmarks:setQuestionMark(q,s.bookmarks)}))}/><IconToggle kind="flag" active={session.flagged.includes(q.id)} onClick={()=>update(s=>s.active?{...s,active:{...s.active,flagged:s.active.flagged.includes(q.id)?s.active.flagged.filter(id=>id!==q.id):[...s.active.flagged,q.id]}}:s)}/></div></div>
    <div className="selection-rule">{q.required>1?`Chọn ${q.required} đáp án · Đã chọn ${answers.length}/${q.required}`:'Chọn một đáp án chính xác nhất'}{!immediate&&<span><EyeOff size={13}/> Đáp án được ẩn đến khi nộp bài</span>}</div>
    <QuestionText question={q} allowHint={session.mode==='practice' && session.settings.feedback==='immediate'}/><ChoiceList question={q} selected={answers} onSelect={choose} disabled={revealed} revealed={revealed}/>
    {immediate && !revealed && <div className="check-answer-row"><span>Chọn đủ đáp án rồi kiểm tra để xem giải thích.</span><button className="button primary" disabled={answers.length!==q.required} onClick={()=>update(s=>revealAnswer(s,q))}><CheckCircle2 size={17}/> Kiểm tra đáp án</button></div>}
    {revealed && <div aria-live="polite"><div className={`feedback-banner ${q.status==='review'?'neutral':isCorrect(q,answers)?'success':'error'}`}>{q.status==='review'?'Câu cần xác minh · Không tính điểm':isCorrect(q,answers)?'Chính xác! Thêm một kiến thức đã nắm vững.':'Chưa chính xác. Cùng xem lại cách giải nhé.'}</div><Explanation question={q} selected={answers}/></div>}
    </main><aside className={`panel question-navigator ${palette?'show-mobile':''}`}><div className="section-heading"><h2>Danh sách câu</h2><Grid2X2 size={18}/></div><div className="progress-caption"><span>Tiến độ trả lời</span><strong>{Math.round(answered/session.questionIds.length*100)}%</strong></div><div className="progress-track"><div style={{width:`${answered/session.questionIds.length*100}%`}}/></div><div className="question-grid">{session.questionIds.map((id,i)=><button key={id} onClick={()=>update(s=>s.active?{...s,active:{...s.active,index:i}}:s)} aria-label={`Đến câu ${i+1}${session.flagged.includes(id)?', đã đánh dấu':''}`} aria-current={i===session.index?'step':undefined} className={`${session.answers[id]?.length?'answered':''} ${i===session.index?'current':''} ${session.flagged.includes(id)?'flagged':''}`}>{i+1}{session.flagged.includes(id)&&<Flag size={8} fill="currentColor"/>}</button>)}</div><div className="navigator-legend"><span><i className="answered"/>Đã trả lời</span><span><i/>Chưa trả lời</span><span><Flag size={12}/>Xem lại ({session.flagged.length})</span></div><div className="navigator-tip"><strong>Mẹo nhỏ</strong><p>Đánh dấu câu cần suy nghĩ thêm và quay lại trước khi nộp.</p><span>← → Chuyển câu · 1–6 Chọn đáp án</span></div></aside></div>
    <footer className="session-footer"><button className="button secondary" onClick={()=>navigate(-1)} disabled={session.index===0}><ArrowLeft size={16}/><span>Câu trước</span></button><button className="button secondary mobile-palette" onClick={()=>setPalette(v=>!v)}><Grid2X2 size={16}/>{palette?'Ẩn':'Các câu'}</button><span className="session-footer-label">{session.flagged.includes(q.id)?'⚑ Đã đánh dấu xem lại':`Câu ${session.index+1} trên ${session.questionIds.length}`}</span><div><button className="button secondary" onClick={()=>setConfirm(true)}><Send size={16}/>Nộp bài</button>{session.index<session.questionIds.length-1&&<button className="button primary" onClick={()=>navigate(1)}>Câu tiếp<ArrowRight size={16}/></button>}</div></footer>
    {confirm&&<Dialog title="Sẵn sàng nộp bài?" confirmLabel="Nộp và xem kết quả" onClose={()=>setConfirm(false)} onConfirm={finish}><p>Bạn đã trả lời <strong>{answered}/{session.questionIds.length}</strong> câu. {session.questionIds.length-answered>0&&`${session.questionIds.length-answered} câu chưa trả lời sẽ được tính là chưa đúng.`}</p>{session.flagged.length>0&&<p>Còn <strong>{session.flagged.length} câu</strong> được đánh dấu xem lại.</p>}<p>Sau khi nộp, bạn có thể xem đáp án và giải thích cho toàn bộ bài.</p></Dialog>}
  </div>;
}

export function Results({session,bank,go}: {session:Session;bank:Question[];go:(path:string)=>void}) {
  const [filter,setFilter]=useState('all');
  const result=score(session,bank), questions=session.questionIds.map(id=>bank.find(q=>q.id===id)!);
  const wrong=questions.filter(q=>q.status!=='review'&&!isCorrect(q,session.answers[q.id])).length;
  const shown=questions.filter(q=>filter==='all'||filter==='wrong'&&q.status!=='review'&&!isCorrect(q,session.answers[q.id])||filter==='flagged'&&session.flagged.includes(q.id));
  return <div className="page results-page"><div className="page-heading"><div className="eyebrow">SESSION COMPLETE</div><h1>Một bước tiến nữa. Làm tốt lắm!</h1><p>{session.finishReason==='timeout'?'Hết thời gian. Bài làm đã được tự động nộp và lưu.':'Bài làm đã được lưu. Dành vài phút xem lại để nhớ lâu hơn.'}</p></div><section className="results-summary panel"><div className="score-ring" style={{background:`conic-gradient(var(--green) ${result.percent}%, #e8efeb 0)`}}><div><strong>{result.total?`${result.percent}%`:'—'}</strong><span>TỶ LỆ ĐÚNG</span></div></div><div className="result-numbers"><div><strong>{result.correct}<small> / {result.total}</small></strong><span>Câu trả lời đúng</span></div><div><strong>{wrong}</strong><span>Sai hoặc bỏ trống</span></div><div><strong>{formatTime(session.finishedAt!-session.startedAt)}</strong><span>Thời gian làm bài</span></div></div><button className="button primary" onClick={()=>go(session.mode==='exam'?'/exam':'/practice')}>Tạo phiên mới<ArrowRight size={17}/></button></section><p className="result-note">Chấm theo khóa đáp án của từng câu; câu “Theo nguồn” chưa được kiểm chứng AWS. Chọn nhiều phải khớp toàn bộ. Đây là tỷ lệ đúng của bài luyện, không quy đổi thành điểm AWS.{result.skipped>0&&` ${result.skipped} câu cần xác minh được loại khỏi mẫu số tính điểm.`}</p><div className="section-heading"><h2>Xem lại bài làm</h2><div className="filter-tabs">{[['all',`Tất cả (${questions.length})`],['wrong',`Cần ôn lại (${wrong})`],['flagged',`Đánh dấu (${session.flagged.length})`]].map(([value,label])=><button className={filter===value?'active':''} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="review-list">{shown.length?shown.map(q=><details className="panel review-card" key={q.id}><summary><span className={`review-status ${q.status==='review'?'neutral':isCorrect(q,session.answers[q.id])?'success':'error'}`}>{q.status==='review'?'?':isCorrect(q,session.answers[q.id])?'✓':'×'}</span><span><small>Câu {questions.indexOf(q)+1} · Ngân hàng #{q.id}</small><strong>{q.text}</strong></span><ArrowRight size={16}/></summary><div className="review-body"><QuestionText question={q} allowHint={session.mode==='practice' && session.settings.feedback==='immediate'}/><ChoiceList question={q} selected={session.answers[q.id]||[]} disabled revealed/><Explanation question={q} selected={session.answers[q.id]||[]}/></div></details>):<div className="panel empty"><CheckCircle2 size={30}/><h3>Không có câu trong nhóm này</h3><p>Chọn “Tất cả” để xem toàn bộ bài làm.</p></div>}</div></div>;
}
