import { ArrowRight, Check, Clock3, Eye, EyeOff, Info, ListChecks, Shuffle } from 'lucide-react';
import { useState } from 'react';
import type { Question, Session, Settings, State } from './domain';
import { defaultSettings, eligibleQuestions, questionRanges, collectionLabel, studyQuestions } from './domain';

export default function Setup({ mode, bank, state, start }: { mode: Session['mode']; bank: Question[]; state: State; start: (settings: Settings, mode: Session['mode']) => void }) {
  const exam = mode === 'exam';
  const [settings, setSettings] = useState<Settings>({ ...defaultSettings, count: exam ? 65 : 20, minutes: 130, feedback: exam ? 'end' : 'immediate' });
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(s => ({...s, [key]:value}));
  const pool = eligibleQuestions(bank, settings, state, mode);
  const valid = Number.isInteger(settings.count) && settings.count >= 1 && settings.count <= pool.length && (!exam || Number.isInteger(settings.minutes) && settings.minutes >= 1 && settings.minutes <= 600);
  return <div className="page setup-page"><div className="page-heading"><div className="eyebrow">{exam ? 'EXAM SIMULATOR' : 'PRACTICE MODE'}</div><h1>{exam ? 'Một buổi thi, theo cách của bạn.' : 'Hiểu từng câu, nhớ lâu hơn.'}</h1><p>{exam ? 'Chọn số câu, đặt thời gian và dành trọn sự tập trung.' : 'Chọn cách xem đáp án và phần kiến thức bạn muốn ôn.'}</p></div>
    <div className="setup-grid"><form className="panel setup-form" onSubmit={e => {e.preventDefault();if(valid)start(settings,mode);}}>
      <div className="form-section"><div className="form-heading"><span>01</span><h2>Chọn bộ câu hỏi</h2></div><div className="field-row"><label>Bộ đề<select aria-label="Bộ đề" value={settings.collection || 'all'} onChange={e=>setSettings(s=>({...s,collection:e.target.value as Settings['collection'],range:'all'}))}><option value="all">Kết hợp MLS + MLA-C01</option><option value="mls">MLS · {studyQuestions(bank).filter(q=>q.collection==='mls').length} câu</option><option value="mla">MLA-C01 · Bộ bổ sung</option></select></label><label>Nội dung<select value={settings.range} onChange={e => set('range',e.target.value)}><option value="all">Toàn bộ ngân hàng câu hỏi</option>{questionRanges.filter(r=>!settings.collection||settings.collection==='all'||r.collection===settings.collection).map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label><label>Ưu tiên ôn<select value={settings.scope} onChange={e => set('scope',e.target.value as Settings['scope'])}><option value="all">Tất cả câu hỏi</option><option value="wrong">Câu trả lời sai gần nhất</option><option value="bookmarked">Câu đã lưu</option><option value="unseen">Câu chưa luyện</option></select></label></div>
      <label className="check-label"><input type="checkbox" checked={settings.includeSource !== false} onChange={e=>set('includeSource',e.target.checked)}/><span>Bao gồm đáp án theo nguồn <small>Chưa kiểm chứng AWS; chấm theo khóa của bộ đề bổ sung</small></span></label>
      <label className="check-label"><input type="checkbox" checked={settings.includeHistorical} onChange={e=>set('includeHistorical',e.target.checked)}/><span>Bao gồm câu về dịch vụ cũ <small>Có ghi chú bối cảnh khi xem đáp án</small></span></label>
      {!exam && <label className="check-label"><input type="checkbox" checked={settings.includeReview} onChange={e=>set('includeReview',e.target.checked)}/><span>Đọc thêm câu cần xác minh <small>{bank.filter(q=>q.status==='review').length} câu này không tính điểm</small></span></label>}
      <div className={`pool-count ${!pool.length?'no-pool':''}`}><Check size={15}/>{pool.length} câu phù hợp với bộ lọc{!pool.length && ' · Hãy thay đổi bộ lọc để bắt đầu.'}</div></div>
      <div className="form-section"><div className="form-heading"><span>02</span><h2>{exam?'Thiết lập bài thi':'Độ dài phiên học'}</h2></div><div className="field-row"><label>Số câu hỏi<input type="number" min="1" max={pool.length} value={settings.count} onChange={e=>set('count',e.target.valueAsNumber || 0)}/></label>{exam && <label>Thời gian (phút)<input type="number" min="1" max="600" value={settings.minutes} onChange={e=>set('minutes',e.target.valueAsNumber || 0)}/></label>}</div><div className="preset-row">{[10,20,50,65].map(n=><button type="button" key={n} className={settings.count===n?'selected':''} onClick={()=>set('count',n)} disabled={n>pool.length}>{n} câu</button>)}<button type="button" onClick={()=>set('count',pool.length)} disabled={!pool.length}>Tất cả</button></div>
      <label className="field-label">Thứ tự câu hỏi</label><div className="segmented"><button type="button" aria-pressed={settings.order==='random'} className={settings.order==='random'?'active':''} onClick={()=>set('order','random')}><Shuffle size={16}/>Ngẫu nhiên</button><button type="button" aria-pressed={settings.order==='sequential'} className={settings.order==='sequential'?'active':''} onClick={()=>set('order','sequential')}><ListChecks size={16}/>Theo thứ tự</button></div></div>
      {!exam && <div className="form-section"><div className="form-heading"><span>03</span><h2>Cách xem đáp án</h2></div><div className="feedback-options">{[{value:'immediate',title:'Học cùng đáp án',desc:'Bấm kiểm tra sau mỗi câu để xem đáp án và giải thích.',icon:Eye},{value:'end',title:'Tự kiểm tra',desc:'Ẩn đáp án trong cả phiên. Chỉ xem sau khi nộp bài.',icon:EyeOff}].map(({value,title,desc,icon:Icon})=><button type="button" key={value} className={`feedback-option ${settings.feedback===value?'selected':''}`} aria-pressed={settings.feedback===value} onClick={()=>set('feedback',value as Settings['feedback'])}><Icon size={20}/><span><strong>{title}</strong><small>{desc}</small></span><span className="radio-dot"/></button>)}</div></div>}
      <button className="button primary start-button" type="submit" disabled={!valid}>{exam?'Bắt đầu thi thử':'Bắt đầu luyện tập'}<ArrowRight size={18}/></button>{!valid && pool.length>0 && <p className="field-error" role="alert">Chọn từ 1 đến {pool.length} câu{exam?' và thời gian từ 1 đến 600 phút':''}.</p>}
    </form><aside className="setup-aside"><div className="exam-ticket"><div className="eyebrow">PHIÊN HỌC CỦA BẠN</div><span className="ticket-icon">{exam?<Clock3 size={34}/>:<ListChecks size={34}/>}</span><h2>{collectionLabel(settings.collection || 'all')}</h2><p>Trạng thái đáp án được ghi ở từng câu</p><div className="ticket-divider"/><div className="ticket-row"><span>Số câu</span><strong>{settings.count}</strong></div><div className="ticket-row"><span>Thời gian</span><strong>{exam?`${settings.minutes} phút`:'Không giới hạn'}</strong></div><div className="ticket-row"><span>Đáp án</span><strong>{exam||settings.feedback==='end'?'Sau khi nộp':'Sau mỗi câu'}</strong></div><div className="ticket-row"><span>Tiến trình</span><strong>Tự động lưu</strong></div></div><div className="aside-note"><Info size={18}/><div><strong>{exam?'Trước khi bắt đầu':'Học theo nhịp của bạn'}</strong><p>{exam?'Đồng hồ vẫn chạy khi đổi tab hoặc tải lại trang. Hết giờ, bài được tự động nộp. Câu chọn nhiều chỉ đúng khi chọn đủ và chính xác.':'Bạn có thể dừng và quay lại bất cứ lúc nào. Câu cần xác minh được giải thích riêng, không chấm đúng hoặc sai.'}</p></div></div><p className="subtle">Giao diện mô phỏng để tự ôn tập, không phải phần mềm OnVUE chính thức.</p></aside></div>
  </div>;
}
